version: '3.7'
services:
  backend:
    environment:
      - environment=${environment}
      - REMOVE_BG_API_KEY=${REMOVE_BG_API_KEY}
      - HANDLER_URL=${HANDLER_URL}
    build: .
    command: gunicorn --bind 0.0.0.0:4000 run:app --workers 8 --threads 8 -k gthread --timeout 10
    restart: always
    volumes:
      - /tmp/photo-id/:/tmp/photo-id/
      - /tmp/photo-id/logs/:/tmp/photo-id/logs/
    ports:
      - 4000:4000